// Code generated by xns-informer-gen. DO NOT EDIT.
package v1

import (
	"fmt"

	xnsinformers "github.com/maistra/xns-informer/pkg/informers"
	v1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	informers "k8s.io/client-go/informers/core/v1"
	listers "k8s.io/client-go/listers/core/v1"
	"k8s.io/client-go/tools/cache"
)

type configMapInformer struct {
	factory xnsinformers.InformerFactory
}

var _ informers.ConfigMapInformer = &configMapInformer{}

func (f *configMapInformer) resource() schema.GroupVersionResource {
	return v1.SchemeGroupVersion.WithResource("configmaps")
}

func (f *configMapInformer) Informer() cache.SharedIndexInformer {
	return f.factory.ForResource(f.resource()).Informer()
}

func (f *configMapInformer) Lister() listers.ConfigMapLister {
	return &configMapLister{lister: f.factory.ForResource(f.resource()).Lister()}
}

type configMapLister struct {
	lister cache.GenericLister
}

var _ listers.ConfigMapLister = &configMapLister{}

func (l *configMapLister) List(selector labels.Selector) (res []*v1.ConfigMap, err error) {
	return listConfigMap(l.lister, selector)
}

func (l *configMapLister) ConfigMaps(namespace string) listers.ConfigMapNamespaceLister {
	return &configMapNamespaceLister{lister: l.lister.ByNamespace(namespace)}
}

type configMapNamespaceLister struct {
	lister cache.GenericNamespaceLister
}

var _ listers.ConfigMapNamespaceLister = &configMapNamespaceLister{}

func (l *configMapNamespaceLister) List(selector labels.Selector) (res []*v1.ConfigMap, err error) {
	return listConfigMap(l.lister, selector)
}

func (l *configMapNamespaceLister) Get(name string) (*v1.ConfigMap, error) {
	obj, err := l.lister.Get(name)
	if err != nil {
		return nil, err
	}

	return convertConfigMap(obj)
}

func listConfigMap(l xnsinformers.SimpleLister, s labels.Selector) (res []*v1.ConfigMap, err error) {
	objects, err := l.List(s)
	if err != nil {
		return nil, err
	}

	for _, obj := range objects {
		o, err := convertConfigMap(obj)
		if err != nil {
			return nil, err
		}

		res = append(res, o)
	}

	return res, nil
}

func convertConfigMap(obj runtime.Object) (*v1.ConfigMap, error) {
	u, ok := obj.(*unstructured.Unstructured)
	if !ok {
		return nil, fmt.Errorf("unstructured conversion failed")
	}

	out := &v1.ConfigMap{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out)
	if err != nil {
		return nil, err
	}

	return out, nil
}
