// Code generated by xns-informer-gen. DO NOT EDIT.
package v1

import (
	xnsinformers "github.com/maistra/xns-informer/pkg/informers"
	v1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	informers "k8s.io/client-go/informers/core/v1"
	listers "k8s.io/client-go/listers/core/v1"
	"k8s.io/client-go/tools/cache"
)

type replicationControllerInformer struct {
	factory xnsinformers.InformerFactory
}

var _ informers.ReplicationControllerInformer = &replicationControllerInformer{}

func (f *replicationControllerInformer) resource() schema.GroupVersionResource {
	return v1.SchemeGroupVersion.WithResource("replicationcontrollers")
}

func (f *replicationControllerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.NamespacedResource(f.resource()).Informer()
}

func (f *replicationControllerInformer) Lister() listers.ReplicationControllerLister {
	idx := xnsinformers.NewCacheConverter(f.Informer().GetIndexer(), &v1.ReplicationController{})
	return listers.NewReplicationControllerLister(idx)
}
